version: '3.7'

services:
  knockknock:
    container_name: knock-knock-django
    restart: always
    build:
      context: .
    environment: 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ALLOWED_URL=${CORS_ALLOWED_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG_VAL=${DEBUG_VAL}
      - PORT=${PORT}
    volumes:
      - static_data:/vol/web
      - ./:/knockkncok
    # command: sh -c "python manage.py runserver 0.0.0.0:${PORT}"
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db

  proxy:
    build: 
      context: ./proxy
    volumes: 
      - static_data:/vol/static
    ports:
      - '8989:8989'
    depends_on:
      - knockknock

  db:
    image: postgres:13
    container_name: knock-knock-postgres-instance
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgresql:/var/lib/postgresql/data

volumes:
  static_data:
  api_data: